package com.kirey.kjcore.data.entity;

// Generated Apr 16, 2013 12:13:47 PM by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * BatchJobParamsId generated by hbm2java
 */
@Embeddable
public class BatchJobExecutionParamsId implements java.io.Serializable {

	private long jobInstanceId;
	private String typeCd;
	private String keyName;
	private String stringVal;
	private Date dateVal;
	private Long longVal;
	private Double doubleVal;

	public BatchJobExecutionParamsId() {
	}

	public BatchJobExecutionParamsId(long jobInstanceId, String typeCd, String keyName) {
		this.jobInstanceId = jobInstanceId;
		this.typeCd = typeCd;
		this.keyName = keyName;
	}

	public BatchJobExecutionParamsId(long jobInstanceId, String typeCd, String keyName,
			String stringVal, Date dateVal, Long longVal, Double doubleVal) {
		this.jobInstanceId = jobInstanceId;
		this.typeCd = typeCd;
		this.keyName = keyName;
		this.stringVal = stringVal;
		this.dateVal = dateVal;
		this.longVal = longVal;
		this.doubleVal = doubleVal;
	}

	@Column(name = "job_instance_id", nullable = false)
	public long getJobInstanceId() {
		return this.jobInstanceId;
	}

	public void setJobInstanceId(long jobInstanceId) {
		this.jobInstanceId = jobInstanceId;
	}

	@Column(name = "type_cd", nullable = false, length = 6)
	public String getTypeCd() {
		return this.typeCd;
	}

	public void setTypeCd(String typeCd) {
		this.typeCd = typeCd;
	}

	@Column(name = "key_name", nullable = false, length = 100)
	public String getKeyName() {
		return this.keyName;
	}

	public void setKeyName(String keyName) {
		this.keyName = keyName;
	}

	@Column(name = "string_val", length = 250)
	public String getStringVal() {
		return this.stringVal;
	}

	public void setStringVal(String stringVal) {
		this.stringVal = stringVal;
	}

	@Column(name = "date_val", length = 29)
	public Date getDateVal() {
		return this.dateVal;
	}

	public void setDateVal(Date dateVal) {
		this.dateVal = dateVal;
	}

	@Column(name = "long_val")
	public Long getLongVal() {
		return this.longVal;
	}

	public void setLongVal(Long longVal) {
		this.longVal = longVal;
	}

	@Column(name = "double_val", precision = 17, scale = 17)
	public Double getDoubleVal() {
		return this.doubleVal;
	}

	public void setDoubleVal(Double doubleVal) {
		this.doubleVal = doubleVal;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof BatchJobExecutionParamsId))
			return false;
		BatchJobExecutionParamsId castOther = (BatchJobExecutionParamsId) other;

		return (this.getJobInstanceId() == castOther.getJobInstanceId())
				&& ((this.getTypeCd() == castOther.getTypeCd()) || (this
						.getTypeCd() != null && castOther.getTypeCd() != null && this
						.getTypeCd().equals(castOther.getTypeCd())))
				&& ((this.getKeyName() == castOther.getKeyName()) || (this
						.getKeyName() != null && castOther.getKeyName() != null && this
						.getKeyName().equals(castOther.getKeyName())))
				&& ((this.getStringVal() == castOther.getStringVal()) || (this
						.getStringVal() != null
						&& castOther.getStringVal() != null && this
						.getStringVal().equals(castOther.getStringVal())))
				&& ((this.getDateVal() == castOther.getDateVal()) || (this
						.getDateVal() != null && castOther.getDateVal() != null && this
						.getDateVal().equals(castOther.getDateVal())))
				&& ((this.getLongVal() == castOther.getLongVal()) || (this
						.getLongVal() != null && castOther.getLongVal() != null && this
						.getLongVal().equals(castOther.getLongVal())))
				&& ((this.getDoubleVal() == castOther.getDoubleVal()) || (this
						.getDoubleVal() != null
						&& castOther.getDoubleVal() != null && this
						.getDoubleVal().equals(castOther.getDoubleVal())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getJobInstanceId();
		result = 37 * result
				+ (getTypeCd() == null ? 0 : this.getTypeCd().hashCode());
		result = 37 * result
				+ (getKeyName() == null ? 0 : this.getKeyName().hashCode());
		result = 37 * result
				+ (getStringVal() == null ? 0 : this.getStringVal().hashCode());
		result = 37 * result
				+ (getDateVal() == null ? 0 : this.getDateVal().hashCode());
		result = 37 * result
				+ (getLongVal() == null ? 0 : this.getLongVal().hashCode());
		result = 37 * result
				+ (getDoubleVal() == null ? 0 : this.getDoubleVal().hashCode());
		return result;
	}

}
