package com.kirey.kjcore.data.entity;
// Generated 20-Oct-2016 11:22:32 by Hibernate Tools 4.3.1.Final

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.annotations.Cascade;
import org.hibernate.annotations.CascadeType;
import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;
import org.hibernate.annotations.LazyCollection;
import org.hibernate.annotations.LazyCollectionOption;

/**
 * KjcDictionary generated by hbm2java
 */
@Entity
@Table(name = "KJC_DICTIONARY")
public class KjcDictionary implements java.io.Serializable {

	private static final long serialVersionUID = 4475072901182374119L;
	private String genericName;
	private String defaultTranslation;
	private List<KjcResourceBundle> kjcResourceBundles = new ArrayList<KjcResourceBundle>(0);

	public KjcDictionary() {
	}

	public KjcDictionary(String genericName, String defaultTranslation) {
		this.genericName = genericName;
		this.defaultTranslation = defaultTranslation;
	}

	public KjcDictionary(String genericName, String defaultTranslation, List<KjcResourceBundle> kjcResourceBundles) {
		this.genericName = genericName;
		this.defaultTranslation = defaultTranslation;
		this.kjcResourceBundles = kjcResourceBundles;
	}

	@Id
	@Column(name = "GENERIC_NAME", unique = true, nullable = false)
	public String getGenericName() {
		return this.genericName;
	}

	public void setGenericName(String genericName) {
		this.genericName = genericName;
	}

	@Column(name = "DEFAULT_TRANSLATION", nullable = false, length = 4000)
	public String getDefaultTranslation() {
		return this.defaultTranslation;
	}

	public void setDefaultTranslation(String defaultTranslation) {
		this.defaultTranslation = defaultTranslation;
	}

	@OneToMany(mappedBy = "kjcDictionary")
	@LazyCollection(LazyCollectionOption.FALSE)
	@Cascade(value = CascadeType.ALL)
	@Fetch(FetchMode.SUBSELECT)
	public List<KjcResourceBundle> getKjcResourceBundles() {
		return this.kjcResourceBundles;
	}

	public void setKjcResourceBundles(List<KjcResourceBundle> kjcResourceBundles) {
		this.kjcResourceBundles = kjcResourceBundles;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((genericName == null) ? 0 : genericName.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		KjcDictionary other = (KjcDictionary) obj;
		if (genericName == null) {
			if (other.genericName != null)
				return false;
		} else if (!genericName.equals(other.genericName))
			return false;
		return true;
	}

	
}
