package com.kirey.kjcore.data.entity;
// Generated 20-Oct-2016 11:22:32 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.validation.constraints.Size;

import org.hibernate.annotations.Cascade;
import org.hibernate.annotations.CascadeType;
import org.hibernate.validator.constraints.NotBlank;

import com.kirey.kjcore.common.constants.ValidationErrorConstants;
import com.kirey.kjcore.data.annotations.CreationUser;
import com.kirey.kjcore.data.annotations.UpdateUser;

/**
 * KjcEmailTemplates generated by hbm2java
 */
@Entity
@Table(name = "KJC_EMAIL_TEMPLATES", uniqueConstraints = @UniqueConstraint(columnNames = "NAME") )
public class KjcEmailTemplates implements java.io.Serializable {

	private static final long serialVersionUID = 4824635034594508733L;
	private Integer id;
	
	@NotBlank(message=ValidationErrorConstants.VALIDATION_BUSINESS_EMAIL_TEMPLATE_FIELD_CANNOT_BE_EMPTY)
	@Size(min=1, max=255, message=ValidationErrorConstants.VALIDATION_FORMAL_EMAIL_TEMPLATE_NAME)
	private String name;
	private byte[] template;
	private Integer utInsert;
	private Date tsInsert;
	private Integer utUpdate;
	private Date tsUpdate;
	
	@NotBlank(message=ValidationErrorConstants.VALIDATION_BUSINESS_EMAIL_TEMPLATE_FIELD_CANNOT_BE_EMPTY)
	@Size(min=1, max=200, message=ValidationErrorConstants.VALIDATION_FORMAL_EMAIL_TEMPLATE_EMAIL_SUBJECT)
	private String emailSubject;
	
	@Size(max=1000, message=ValidationErrorConstants.VALIDATION_FORMAL_EMAIL_TEMPLATE_DESCRIPTION)
	private String description;
	private Set<KjcInlineResourceTemplates> kjcInlineResourceTemplateses = new HashSet<KjcInlineResourceTemplates>(0);

	public KjcEmailTemplates() {
	}
	
	public KjcEmailTemplates(Integer id, String name, byte[] template, Integer utInsert, Date tsInsert,
			Integer utUpdate, Date tsUpdate, String emailSubject) {
		this.id = id;
		this.name = name;
		this.template = template;
		this.utInsert = utInsert;
		this.tsInsert = tsInsert;
		this.utUpdate = utUpdate;
		this.tsUpdate = tsUpdate;
		this.emailSubject = emailSubject;
	}

	public KjcEmailTemplates(Integer id, String name, byte[] template, Integer utInsert, Date tsInsert,
			Integer utUpdate, Date tsUpdate, String emailSubject, String description,
			Set<KjcInlineResourceTemplates> kjcInlineResourceTemplateses) {
		this.id = id;
		this.name = name;
		this.template = template;
		this.utInsert = utInsert;
		this.tsInsert = tsInsert;
		this.utUpdate = utUpdate;
		this.tsUpdate = tsUpdate;
		this.emailSubject = emailSubject;
		this.description = description;
		this.kjcInlineResourceTemplateses = kjcInlineResourceTemplateses;
	}

	@Id
	@SequenceGenerator(name = "SEQ_KJC_EMAIL_TEMPLATES_GEN", sequenceName = "SEQ_KJC_EMAIL_TEMPLATES", allocationSize = 1, initialValue = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "SEQ_KJC_EMAIL_TEMPLATES_GEN")
	@Column(name = "ID", unique = true, nullable = false, precision = 10, scale = 0)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "NAME", unique = true, nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "TEMPLATE", nullable = false)
	public byte[] getTemplate() {
		return this.template;
	}

	public void setTemplate(byte[] template) {
		this.template = template;
	}

	@Column(name = "UT_INSERT", updatable=false, nullable = false, precision = 10, scale = 0)
	@CreationUser
	public Integer getUtInsert() {
		return this.utInsert;
	}

	public void setUtInsert(Integer utInsert) {
		this.utInsert = utInsert;
	}

	@Column(name = "TS_INSERT", updatable=false, nullable = false)
	@org.hibernate.annotations.CreationTimestamp
	public Date getTsInsert() {
		return this.tsInsert;
	}

	public void setTsInsert(Date tsInsert) {
		this.tsInsert = tsInsert;
	}

	@Column(name = "UT_UPDATE", nullable = false, precision = 10, scale = 0)
	@UpdateUser
	public Integer getUtUpdate() {
		return this.utUpdate;
	}

	public void setUtUpdate(Integer utUpdate) {
		this.utUpdate = utUpdate;
	}

	@Column(name = "TS_UPDATE", nullable = false)
	@org.hibernate.annotations.UpdateTimestamp
	public Date getTsUpdate() {
		return this.tsUpdate;
	}

	public void setTsUpdate(Date tsUpdate) {
		this.tsUpdate = tsUpdate;
	}

	@Column(name = "EMAIL_SUBJECT", nullable = false, length = 200)
	public String getEmailSubject() {
		return this.emailSubject;
	}

	public void setEmailSubject(String emailSubject) {
		this.emailSubject = emailSubject;
	}

	@Column(name = "DESCRIPTION", length = 1000)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "kjcEmailTemplates")
	@Cascade(value = CascadeType.ALL)
	public Set<KjcInlineResourceTemplates> getKjcInlineResourceTemplateses() {
		return this.kjcInlineResourceTemplateses;
	}

	public void setKjcInlineResourceTemplateses(Set<KjcInlineResourceTemplates> kjcInlineResourceTemplateses) {
		this.kjcInlineResourceTemplateses = kjcInlineResourceTemplateses;
	}

}
