package com.kirey.kjcore.data.entity;
// Generated 04-Nov-2016 09:47:41 by Hibernate Tools 4.3.1.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * KjcErrorLogs generated by hbm2java
 */
@Entity
@Table(name = "KJC_ERROR_LOGS")
public class KjcErrorLogs implements java.io.Serializable {

	private static final long serialVersionUID = 1461833907810504832L;

	private Integer id;
	private Date thrownDate;
	private String errorName;
	private String invokingUrl;
	private String message;
	private String username;
	private String processType;
	private String processCategory;
	private String taskId;
	private Integer batchJobInstanceId;
	
	@JsonIgnore
	//@Transient
	private KjcErrorTraces kjcErrorTraces;


	public KjcErrorLogs() {
	}

	public KjcErrorLogs(Integer id, Date thrownDate, String errorName, String username, String processType,
			String processCategory) {
		this.id = id;
		this.thrownDate = thrownDate;
		this.errorName = errorName;
		this.username = username;
		this.processType = processType;
		this.processCategory = processCategory;
	}

	public KjcErrorLogs(Integer id, Date thrownDate, String errorName, String invokingUrl, String message,
			String username, String processType, String processCategory, KjcErrorTraces kjcErrorTraces, String taskId) {
		this.id = id;
		this.thrownDate = thrownDate;
		this.errorName = errorName;
		this.invokingUrl = invokingUrl;
		this.message = message;
		this.username = username;
		this.processType = processType;
		this.processCategory = processCategory;
		//this.kjcErrorTraces = kjcErrorTraces;
		this.taskId = taskId;
	}

	@Id
	@SequenceGenerator(name = "err_log_gen", sequenceName = "SEQ_KJC_ERROR_LOGS", allocationSize = 1, initialValue = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "err_log_gen")
	@Column(name = "ID", unique = true, nullable = false, precision = 10, scale = 0)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "THROWN_DATE", nullable = false, length = 7)
	public Date getThrownDate() {
		return this.thrownDate;
	}

	public void setThrownDate(Date thrownDate) {
		this.thrownDate = thrownDate;
	}

	@Column(name = "ERROR_NAME", nullable = false)
	public String getErrorName() {
		return this.errorName;
	}

	public void setErrorName(String errorName) {
		this.errorName = errorName;
	}

	@Column(name = "INVOKING_URL", length = 4000)
	public String getInvokingUrl() {
		return this.invokingUrl;
	}

	public void setInvokingUrl(String invokingUrl) {
		this.invokingUrl = invokingUrl;
	}

	@Column(name = "MESSAGE", length = 4000)
	public String getMessage() {
		return this.message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

	@Column(name = "USERNAME", nullable = false)
	public String getUsername() {
		return username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "PROCESS_TYPE", nullable = false, length = 20)
	public String getProcessType() {
		return this.processType;
	}

	public void setProcessType(String processType) {
		this.processType = processType;
	}

	@Column(name = "PROCESS_CATEGORY", nullable = false, length = 30)
	public String getProcessCategory() {
		return this.processCategory;
	}

	public void setProcessCategory(String processCategory) {
		this.processCategory = processCategory;
	}

	@OneToOne(optional = false, fetch = FetchType.LAZY, mappedBy = "kjcErrorLogs")
	public KjcErrorTraces getKjcErrorTraces() {
		return this.kjcErrorTraces;
	}

	public void setKjcErrorTraces(KjcErrorTraces kjcErrorTraces) {
		this.kjcErrorTraces = kjcErrorTraces;
	}
	
	@Column(name = "TASK_ID", length = 50)
	public String getTaskId() {
		return taskId;
	}

	public void setTaskId(String taskId) {
		this.taskId = taskId;
	}

	@Column(name = "batch_job_instance", nullable = true)
	public Integer getBatchJobInstanceId() {
		return batchJobInstanceId;
	}

	public void setBatchJobInstanceId(Integer batchJobInstanceId) {
		this.batchJobInstanceId = batchJobInstanceId;
	}

}
