package com.kirey.kjcore.data.entity;
// Generated 20-Oct-2016 11:22:32 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * KjcErrorTraces generated by hbm2java
 */
@Entity
@Table(name = "KJC_ERROR_TRACES")
public class KjcErrorTraces implements java.io.Serializable {

	private static final long serialVersionUID = 5303855415733616357L;

	private Integer kjcErrorLog;

	private KjcErrorLogs kjcErrorLogs;

	private String trace;

	public KjcErrorTraces() {
	}

	public KjcErrorTraces(KjcErrorLogs kjcErrorLogs, String trace) {
		this.kjcErrorLogs = kjcErrorLogs;
		this.trace = trace;
	}

	@Id
	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "kjcErrorLogs") )
	@GeneratedValue(generator = "generator")
	@Column(name = "KJC_ERROR_LOG", unique = true, nullable = false, precision = 10, scale = 0)
	public Integer getKjcErrorLog() {
		return this.kjcErrorLog;
	}

	public void setKjcErrorLog(Integer kjcErrorLog) {
		this.kjcErrorLog = kjcErrorLog;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public KjcErrorLogs getKjcErrorLogs() {
		return this.kjcErrorLogs;
	}

	public void setKjcErrorLogs(KjcErrorLogs kjcErrorLogs) {
		this.kjcErrorLogs = kjcErrorLogs;
	}

	@Column(name = "TRACE", nullable = false)
	public String getTrace() {
		return this.trace;
	}

	public void setTrace(String trace) {
		this.trace = trace;
	}

}
