package com.kirey.kjcore.data.entity;
// Generated Dec 6, 2016 5:46:52 PM by Hibernate Tools 5.1.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Lob;
import javax.persistence.Table;
import javax.validation.constraints.Size;

import org.hibernate.annotations.Type;

import com.kirey.kjcore.common.constants.ValidationErrorConstants;
import com.kirey.kjcore.data.annotations.CreationUser;
import com.kirey.kjcore.data.annotations.UpdateUser;

/**
 * KjcGenerics generated by hbm2java
 */
@Entity
@Table(name = "KJC_GENERICS")
public class KjcGenerics implements java.io.Serializable {

	@Size(min=1, max=100, message=ValidationErrorConstants.VALIDATION_FORMAL_GENERICS_KEY)
	private String key;
	@Size(min=1, max=1000, message=ValidationErrorConstants.VALIDATION_FORMAL_GENERICS_VALUE)
	private String value;
	@Size(min=1, max=4000, message=ValidationErrorConstants.VALIDATION_FORMAL_GENERICS_DESCRIPTION)
	private String description;
	private String keyType;
	private Integer utInsert;
	private Date tsInsert;
	private Integer utUpdate;
	private Date tsUpdate;
	private byte[] fileBlob;

	public KjcGenerics() {
	}

	public KjcGenerics(String key, String value, String description, String keyType, Integer utInsert, Date tsInsert,
			Integer utUpdate, Date tsUpdate) {
		this.key = key;
		this.value = value;
		this.description = description;
		this.keyType = keyType;
		this.utInsert = utInsert;
		this.tsInsert = tsInsert;
		this.utUpdate = utUpdate;
		this.tsUpdate = tsUpdate;
	}

	@Id
	@Column(name = "KEY", unique = true, nullable = false, length = 100)
	public String getKey() {
		return this.key;
	}

	public void setKey(String key) {
		this.key = key;
	}

	@Column(name = "VALUE", nullable = false, length = 1000)
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	@Column(name = "DESCRIPTION", nullable = false, length = 4000)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}
	
	@Column(name = "KEY_TYPE", nullable = false, length = 50)
	public String getKeyType() {
		return this.keyType;
	}

	public void setKeyType(String keyType) {
		this.keyType = keyType;
	}

	@Column(name = "UT_INSERT", updatable=false, nullable = false, precision = 10, scale = 0)
	@CreationUser
	public Integer getUtInsert() {
		return this.utInsert;
	}

	public void setUtInsert(Integer utInsert) {
		this.utInsert = utInsert;
	}

	@Column(name = "TS_INSERT", updatable=false, nullable = false)
	@org.hibernate.annotations.CreationTimestamp
	public Date getTsInsert() {
		return this.tsInsert;
	}

	public void setTsInsert(Date tsInsert) {
		this.tsInsert = tsInsert;
	}

	@Column(name = "UT_UPDATE", nullable = false, precision = 10, scale = 0)
	@UpdateUser
	public Integer getUtUpdate() {
		return this.utUpdate;
	}

	public void setUtUpdate(Integer utUpdate) {
		this.utUpdate = utUpdate;
	}

	@Column(name = "TS_UPDATE", nullable = false)
	@org.hibernate.annotations.UpdateTimestamp
	public Date getTsUpdate() {
		return this.tsUpdate;
	}

	public void setTsUpdate(Date tsUpdate) {
		this.tsUpdate = tsUpdate;
	}

	//@Lob // in case of use postgres database remove @Lob annotation
	@Column(name = "FILE_BLOB", nullable = true)
	public byte[] getFileBlob() {
		return fileBlob;
	}

	public void setFileBlob(byte[] fileBlob) {
		this.fileBlob = fileBlob;
	}
	
	

}
