package com.kirey.kjcore.data.entity;
// Generated 20-Oct-2016 11:22:32 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import com.fasterxml.jackson.annotation.JsonBackReference;

/**
 * KjcResourceBundle generated by hbm2java
 */
@Entity
@Table(name = "KJC_RESOURCE_BUNDLE", uniqueConstraints = @UniqueConstraint(columnNames = { "GENERIC_NAME",
		"LANGUAGE" }) )
public class KjcResourceBundle implements java.io.Serializable {

	private static final long serialVersionUID = 532690069272385587L;

	private Integer id;

	@JsonBackReference
	private KjcDictionary kjcDictionary;

	private String language;
	private String translation;

	public KjcResourceBundle() {
	}

	public KjcResourceBundle(Integer id, KjcDictionary kjcDictionary, String language, String translation) {
		this.id = id;
		this.kjcDictionary = kjcDictionary;
		this.language = language;
		this.translation = translation;
	}

	@Id
	@SequenceGenerator(name = "rb_gen", sequenceName = "SEQ_KJC_RESOURCE_BUNDLE", allocationSize = 1, initialValue = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "rb_gen")
	@Column(name = "ID", unique = true, nullable = false, precision = 10, scale = 0)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "GENERIC_NAME", nullable = false)
	public KjcDictionary getKjcDictionary() {
		return this.kjcDictionary;
	}

	public void setKjcDictionary(KjcDictionary kjcDictionary) {
		this.kjcDictionary = kjcDictionary;
	}

	@Column(name = "LANGUAGE", nullable = false, length = 10)
	public String getLanguage() {
		return this.language;
	}

	public void setLanguage(String language) {
		this.language = language;
	}

	@Column(name = "TRANSLATION", nullable = false, length = 4000)
	public String getTranslation() {
		return this.translation;
	}

	public void setTranslation(String translation) {
		this.translation = translation;
	}

}
