package com.kirey.kjcore.data.entity;
// Generated 20-Oct-2016 11:22:32 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import com.fasterxml.jackson.annotation.JsonBackReference;

/**
 * KjcReportBookingParameters generated by hbm2java
 */
@Entity
@Table(name = "KJC_REPORT_BOOKING_PARAMETERS", uniqueConstraints = @UniqueConstraint(columnNames = {
		"KJC_REPORT_BOOKING", "KJC_REPORT_PARAMETER" }) )
public class KjcReportBookingParameters implements java.io.Serializable {

	private static final long serialVersionUID = -8072777712419451244L;

	private Integer id;

	@JsonBackReference
	private KjcReportParameters kjcReportParameters;

	@JsonBackReference(value = "booking_parameters")
	private KjcReportBookings kjcReportBookings;

	private String value;

	public KjcReportBookingParameters() {
	}

	public KjcReportBookingParameters(Integer id, KjcReportParameters kjcReportParameters,
			KjcReportBookings kjcReportBookings) {
		this.id = id;
		this.kjcReportParameters = kjcReportParameters;
		this.kjcReportBookings = kjcReportBookings;
	}

	public KjcReportBookingParameters(Integer id, KjcReportParameters kjcReportParameters,
			KjcReportBookings kjcReportBookings, String value) {
		this.id = id;
		this.kjcReportParameters = kjcReportParameters;
		this.kjcReportBookings = kjcReportBookings;
		this.value = value;
	}

	@Id
	@SequenceGenerator(name = "reportparamvalues_gen", sequenceName = "SEQ_KJC_REPORT_BOOKING_PARAM", allocationSize = 1, initialValue = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "reportparamvalues_gen")
	@Column(name = "ID", unique = true, nullable = false, precision = 10, scale = 0)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "KJC_REPORT_PARAMETER", nullable = false)
	public KjcReportParameters getKjcReportParameters() {
		return this.kjcReportParameters;
	}

	public void setKjcReportParameters(KjcReportParameters kjcReportParameters) {
		this.kjcReportParameters = kjcReportParameters;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "KJC_REPORT_BOOKING", nullable = false)
	public KjcReportBookings getKjcReportBookings() {
		return this.kjcReportBookings;
	}

	public void setKjcReportBookings(KjcReportBookings kjcReportBookings) {
		this.kjcReportBookings = kjcReportBookings;
	}

	@Column(name = "VALUE")
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

}
