package com.kirey.kjcore.data.entity;

// default package
// Generated Oct 24, 2016 4:59:14 PM by Hibernate Tools 5.1.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import com.kirey.kjcore.data.annotations.CreationUser;
import com.kirey.kjcore.data.annotations.UpdateUser;

/**
 * KjcSchedulerTraces generated by hbm2java
 */
@Entity
@Table(name = "KJC_SCHEDULER_TRACES")
public class KjcSchedulerTraces implements java.io.Serializable {

	private static final long serialVersionUID = -424688696371948996L;

	private Integer id;
	private KjcTaskSchedulers kjcTaskSchedulers;
	private String status;
	private Integer utInsert;
	private Date tsInsert;
	private Integer utUpdate;
	private Date tsUpdate;

	public KjcSchedulerTraces() {
	}

	public KjcSchedulerTraces(Integer id, KjcTaskSchedulers kjcTaskSchedulers, Integer utInsert, Date tsInsert,
			Integer utUpdate, Date tsUpdate) {
		this.id = id;
		this.kjcTaskSchedulers = kjcTaskSchedulers;
		this.utInsert = utInsert;
		this.tsInsert = tsInsert;
		this.utUpdate = utUpdate;
		this.tsUpdate = tsUpdate;
	}

	public KjcSchedulerTraces(Integer id, KjcTaskSchedulers kjcTaskSchedulers, String status, Integer utInsert,
			Date tsInsert, Integer utUpdate, Date tsUpdate) {
		this.id = id;
		this.kjcTaskSchedulers = kjcTaskSchedulers;
		this.status = status;
		this.utInsert = utInsert;
		this.tsInsert = tsInsert;
		this.utUpdate = utUpdate;
		this.tsUpdate = tsUpdate;
	}

	@Id
	@SequenceGenerator(name = "SEQ_KJC_SCHEDULER_TRACES_GEN", sequenceName = "SEQ_KJC_SCHEDULER_TRACES", allocationSize = 1, initialValue = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "SEQ_KJC_SCHEDULER_TRACES_GEN")
	@Column(name = "ID", unique = true, nullable = false, precision = 10, scale = 0)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "KJC_TASK_SCHEDULER", nullable = false)
	public KjcTaskSchedulers getKjcTaskSchedulers() {
		return this.kjcTaskSchedulers;
	}

	public void setKjcTaskSchedulers(KjcTaskSchedulers kjcTaskSchedulers) {
		this.kjcTaskSchedulers = kjcTaskSchedulers;
	}

	@Column(name = "STATUS", length = 50)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}


	@Column(name = "UT_INSERT", nullable = false, precision = 10, scale = 0)
	@CreationUser
	public Integer getUtInsert() {
		return this.utInsert;
	}

	public void setUtInsert(Integer utInsert) {
		this.utInsert = utInsert;
	}

	@Column(name = "TS_INSERT", nullable = false)
	@org.hibernate.annotations.CreationTimestamp
	public Date getTsInsert() {
		return this.tsInsert;
	}

	public void setTsInsert(Date tsInsert) {
		this.tsInsert = tsInsert;
	}

	@Column(name = "UT_UPDATE", nullable = false, precision = 10, scale = 0)
	@UpdateUser
	public Integer getUtUpdate() {
		return this.utUpdate;
	}

	public void setUtUpdate(Integer utUpdate) {
		this.utUpdate = utUpdate;
	}

	@Column(name = "TS_UPDATE", nullable = false)
	@org.hibernate.annotations.UpdateTimestamp
	public Date getTsUpdate() {
		return this.tsUpdate;
	}

	public void setTsUpdate(Date tsUpdate) {
		this.tsUpdate = tsUpdate;
	}

}
