package com.kirey.kjcore.data.entity;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonBackReference;

/**
 * KjcTaskParameters generated by hbm2java
 */
@Entity
@Table(name = "KJC_TASK_PARAMETERS")
public class KjcTaskParameters implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4715830236880351595L;
	private Integer id;
	@JsonBackReference(value = "parameters")
	private KjcTaskSchedulers kjcTaskSchedulers;
	private String name;
	private String value;
	private Integer utInsert;
	private Date tsInsert;
	private Integer utUpdate;
	private Date tsUpdate;

	public KjcTaskParameters() {
	}

	public KjcTaskParameters(Integer id, String name, String value, Integer utInsert, Date tsInsert, Integer utUpdate,
			Date tsUpdate) {
		this.id = id;
		this.name = name;
		this.value = value;
		this.utInsert = utInsert;
		this.tsInsert = tsInsert;
		this.utUpdate = utUpdate;
		this.tsUpdate = tsUpdate;
	}

	public KjcTaskParameters(Integer id, KjcTaskSchedulers kjcTaskSchedulers, String name, String value,
			Integer utInsert, Date tsInsert, Integer utUpdate, Date tsUpdate) {
		this.id = id;
		this.kjcTaskSchedulers = kjcTaskSchedulers;
		this.name = name;
		this.value = value;
		this.utInsert = utInsert;
		this.tsInsert = tsInsert;
		this.utUpdate = utUpdate;
		this.tsUpdate = tsUpdate;
	}

	@Id
	@SequenceGenerator(name = "SEQ_KJC_TASK_PARAMETERS_GEN", sequenceName = "SEQ_KJC_TASK_PARAMETERS", allocationSize = 1, initialValue = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "SEQ_KJC_TASK_PARAMETERS_GEN")
	@Column(name = "ID", unique = true, nullable = false, precision = 10, scale = 0)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "KJC_TASK_SCHEDULER")
	public KjcTaskSchedulers getKjcTaskSchedulers() {
		return this.kjcTaskSchedulers;
	}

	public void setKjcTaskSchedulers(KjcTaskSchedulers kjcTaskSchedulers) {
		this.kjcTaskSchedulers = kjcTaskSchedulers;
	}

	@Column(name = "NAME", nullable = false, length = 500)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "VALUE", nullable = false, length = 500)
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	@Column(name = "UT_INSERT", nullable = false, precision = 10, scale = 0)
	public Integer getUtInsert() {
		return this.utInsert;
	}

	public void setUtInsert(Integer utInsert) {
		this.utInsert = utInsert;
	}

	@Column(name = "TS_INSERT", nullable = false)
	public Date getTsInsert() {
		return this.tsInsert;
	}

	public void setTsInsert(Date tsInsert) {
		this.tsInsert = tsInsert;
	}

	@Column(name = "UT_UPDATE", nullable = false, precision = 10, scale = 0)
	public Integer getUtUpdate() {
		return this.utUpdate;
	}

	public void setUtUpdate(Integer utUpdate) {
		this.utUpdate = utUpdate;
	}

	@Column(name = "TS_UPDATE", nullable = false)
	public Date getTsUpdate() {
		return this.tsUpdate;
	}

	public void setTsUpdate(Date tsUpdate) {
		this.tsUpdate = tsUpdate;
	}

}
