package com.kirey.kjcore.data.entity;
// Generated Feb 27, 2017 3:27:59 PM by Hibernate Tools 5.2.0.Beta1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.kirey.kjcore.data.annotations.CreationUser;
import com.kirey.kjcore.data.annotations.UpdateUser;
import com.kirey.kjcore.data.entity.KjcUserAccounts;

/**
 * UserAccounts generated by hbm2java
 */
@Entity
@Table(name = "USER_ACCOUNTS")
public class UserAccounts implements java.io.Serializable {

	private static final long serialVersionUID = 5511546694571010371L;
	
	private Integer kjcUserAccount;
	@JsonBackReference
	private KjcUserAccounts kjcUserAccounts;
	private Integer utInsert;
	private Date tsInsert;
	private Integer utUpdate;
	private Date tsUpdate;

	public UserAccounts() {
	}


	public UserAccounts(KjcUserAccounts kjcUserAccounts,
			Integer utInsert, Date tsInsert, Integer utUpdate, Date tsUpdate) {
		this.kjcUserAccounts = kjcUserAccounts;
		this.utInsert = utInsert;
		this.tsInsert = tsInsert;
		this.utUpdate = utUpdate;
		this.tsUpdate = tsUpdate;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "kjcUserAccounts"))
	@Id
	@GeneratedValue(generator = "generator")

	@Column(name = "KJC_USER_ACCOUNT", unique = true, nullable = false, precision = 10, scale = 0)
	public Integer getKjcUserAccount() {
		return this.kjcUserAccount;
	}

	public void setKjcUserAccount(Integer kjcUserAccount) {
		this.kjcUserAccount = kjcUserAccount;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public KjcUserAccounts getKjcUserAccounts() {
		return this.kjcUserAccounts;
	}

	public void setKjcUserAccounts(KjcUserAccounts kjcUserAccounts) {
		this.kjcUserAccounts = kjcUserAccounts;
	}


	@Column(name = "UT_INSERT", updatable=false, precision = 10, scale = 0)
	@CreationUser
	public Integer getUtInsert() {
		return this.utInsert;
	}

	public void setUtInsert(Integer utInsert) {
		this.utInsert = utInsert;
	}

	@Column(name = "TS_INSERT", nullable = false, updatable=false)
	@org.hibernate.annotations.CreationTimestamp
	public Date getTsInsert() {
		return this.tsInsert;
	}

	public void setTsInsert(Date tsInsert) {
		this.tsInsert = tsInsert;
	}

	@Column(name = "UT_UPDATE", precision = 10, scale = 0)
	@UpdateUser
	public Integer getUtUpdate() {
		return this.utUpdate;
	}

	public void setUtUpdate(Integer utUpdate) {
		this.utUpdate = utUpdate;
	}

	@org.hibernate.annotations.UpdateTimestamp
	@Column(name = "TS_UPDATE", nullable = false)
	public Date getTsUpdate() {
		return this.tsUpdate;
	}

	public void setTsUpdate(Date tsUpdate) {
		this.tsUpdate = tsUpdate;
	}
}
